---
extends: default
rules:
  line-length:
    max: 100
    level: error
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 2
  indentation:
    spaces: 2
    indent-sequences: true
